added javadox documentation for Arduino_MachineControl.h
arduino-libraries/Arduino_MachineControl pull request #62
Opened 2021-07-06 08:32 UTC by ErnestoELC

2021-07-06 09:30 UTC, per1234 requested changes

2021-07-06 09:30 UTC, per1234 commented on src/Arduino_MachineControl.h
> +	 * Set the CAN transciever in Normal mode. In this mode, the transceiver
```suggestion
	 * Set the CAN transceiver in Normal mode. In this mode, the transceiver 
```

2021-07-06 09:30 UTC, per1234 commented on src/Arduino_MachineControl.h
> +	 * Set the CAN transciever in standby (low power) mode. In this mode the
```suggestion
	 * Set the CAN transceiver in standby (low power) mode. In this mode the
```

2021-07-06 09:30 UTC, per1234 commented on src/Arduino_MachineControl.h
> +	 * Configure the input resistor deviders to have a ratio of 0.28.
```suggestion
	 * Configure the input resistor dividers to have a ratio of 0.28.
```

2021-07-06 09:30 UTC, per1234 commented on src/Arduino_MachineControl.h
> +	 * Enable a 120 ohm resitor to GND to convert the 4-20mA sensor currents to voltage.
```suggestion
	 * Enable a 120 ohm resistor to GND to convert the 4-20mA sensor currents to voltage. 
```

2021-07-06 09:30 UTC, per1234 commented on src/Arduino_MachineControl.h
> +	 * Enable a 100K resitor in series with the reference voltage.
```suggestion
	 * Enable a 100K resistor in series with the reference voltage.	 
```

2021-07-06 09:30 UTC, per1234 commented on src/Arduino_MachineControl.h
> +	 * @return True if OK, False if fault
```suggestion
	 * @return true if OK, false if fault
```

2021-07-06 09:30 UTC, per1234 commented on src/Arduino_MachineControl.h
> +	 * @return True if OK, False if fault
```suggestion
	 * @return true if OK, false if fault
```

2021-07-06 09:30 UTC, per1234 commented on src/Arduino_MachineControl.h
> +	 * @return True if OK, False if fault
```suggestion
	 * @return true if OK, false if fault
```

2021-07-07 01:06 UTC, per1234 submitted a review, later dismissed

2021-07-07 01:06 UTC, per1234 commented on src/utility/RTC/PCF8563T.cpp
> +// allarm managemet
```suggestion
// alarm management
```

2021-07-07 01:06 UTC, per1234 commented on src/utility/RTC/PCF8563T.cpp
> + *  Initialize I2C (Wire1) bus and check if the chip is connected trhoug sending an ACK on the I2C bus.
```suggestion
 *  Initialize I2C (Wire1) bus and check if the chip is connected by sending an ACK on the I2C bus.
```

2021-07-12 07:22 UTC, sebromero commented
@ErnestoELC Can you have a look at Per's suggestions?

2021-08-23 10:17 UTC, marqdevx approved these changes

2021-08-23 10:18 UTC, marqdevx approved these changes

2021-08-23 10:20 UTC, marqdevx approved these changes

2021-08-23 10:20 UTC, marqdevx approved these changes

2021-08-23 10:21 UTC, marqdevx commented
@per1234 Thanks for the suggestions!
Now I cannot remove the changes requested, how should I?

Thanks again!! :D

2021-08-23 10:22 UTC, marqdevx approved these changes

2021-08-23 10:48 UTC, per1234 commented
@marqdevx I have now dismissed the requests as resolved. Thanks!

2021-08-30 04:24 UTC, merged